re-vendor buildkit

diff --git a/buildkit/buildpacks/php/bin/compile b/buildkit/buildpacks/php/bin/compile
--- a/buildkit/buildpacks/php/bin/compile
+++ b/buildkit/buildpacks/php/bin/compile
@@ -7,17 +7,23 @@ install_ext () {
     local reason=${2:-}
     local ext_ini="$BP_DIR/conf/php/conf.d/ext-$ext.ini"
     local ext_so=
-    local ext_dir=$(basename $(php-config --extension-dir))
+    local ext_dir=$(php-config --extension-dir)
+    local ext_api=$(basename $ext_dir)
     if [[ -f "$ext_ini" ]]; then
         ext_so=$(php -r '$ini=parse_ini_file("'$ext_ini'"); echo $ext=$ini["zend_extension"]?:$ini["extension"]; exit((int)empty($ext));') # read .so name from .ini because e.g. opcache.so is named "zend-opcache"
-        if [[ ! -f "$PHP_EXT_DIR/$ext_so" ]]; then
-            curl --silent --location "${S3_URL}/extensions/${ext_dir}/${ext}.tar.gz" | tar xz -C $BUILD_DIR/.heroku/php
-            echo "- ${ext} (${reason}; downloaded)" | indent
+        if [[ ! -f "$ext_dir/$ext_so" ]]; then
+            if [[ -f "$BP_DIR/support/build/extensions/$ext_api/$ext" ]]; then
+                curl --silent --location "${S3_URL}/extensions/${ext_api}/${ext}.tar.gz" | tar xz -C $BUILD_DIR/.heroku/php
+                echo "- ${ext} (${reason}; downloaded)" | indent
+                cp "${ext_ini}" "${BUILD_DIR}/.heroku/php/etc/php/conf.d"
+            else
+                warning_inline "Unknown extension ${ext} (${reason}), install may fail!"
+            fi
         else
             echo "- ${ext} (${reason}; bundled)" | indent
+            cp "${ext_ini}" "${BUILD_DIR}/.heroku/php/etc/php/conf.d"
         fi
-        cp "${ext_ini}" "${BUILD_DIR}/.heroku/php/etc/php/conf.d"
-    elif [[ -f "${PHP_EXT_DIR}/${ext}.so" ]]; then
+    elif [[ -f "${ext_dir}/${ext}.so" ]]; then
         echo "extension = ${ext}.so" > "${BUILD_DIR}/.heroku/php/etc/php/conf.d/ext-${ext}.ini"
         echo "- ${ext} (${reason}; bundled)" | indent
     elif echo -n ${ext} | php -r 'exit((int)!extension_loaded(file_get_contents("php://stdin")));'; then
@@ -65,18 +71,26 @@ RTVS_URL="https://php-runtime-version-selector.herokuapp.com"
 
 cd $BUILD_DIR
 
-if [[ -s "composer.json" ]]; then
-    cat composer.json | python -mjson.tool &> /dev/null || error "Could not parse composer.json; make sure it's valid!"
+if [[ -n ${COMPOSER:-} ]]; then
+    status "Using '$COMPOSER' (from "'$COMPOSER env var) for installation.'
 else
-    if [[ ! -f "composer.json" ]]; then
-        warning 'No composer.json found.
-Using index.php to declare PHP applications is considered legacy
-functionality and may lead to unexpected behavior.'
+    export COMPOSER="composer.json"
+fi
+COMPOSER_LOCK=$(basename "$COMPOSER" ".json")".lock" # replace .json with .lock if it exists, append .lock otherwise
+
+
+if [[ -s "$COMPOSER" ]]; then
+    cat "$COMPOSER" | python -mjson.tool &> /dev/null || error "Could not parse '$COMPOSER'; make sure it's valid!"
+else
+    if [[ ! -f "$COMPOSER" ]]; then
+        warning "No '$COMPOSER' found.
+Using 'index.php' to declare PHP applications is considered legacy
+functionality and may lead to unexpected behavior."
     else
-        notice 'Your composer.json is completely empty.
-Please change its contents to at least "{}" so it is valid JSON.'
+        notice "Your '$COMPOSER' is completely empty.
+Please change its contents to at least '{}' so it is valid JSON."
     fi
-    echo "{}" > composer.json
+    echo "{}" > $COMPOSER
 fi
 
 mkdir -p .heroku/php
@@ -87,48 +101,68 @@ mkdir -p $COMPOSER_HOME
 PHP_VERSION=
 HHVM_VERSION=
 if [[ "$STACK" == "cedar" ]]; then
-    runtimes=$(cd $BP_DIR/support/build; ls {php-*,hhvm-3.2.0}) # cedar only has HHVM 3.2
+    runtimes=$(cd $BP_DIR/support/build; ls {php-5*,hhvm-3.2.0}) # cedar only has HHVM 3.2 and no PHP 7
 else
     runtimes=$(cd $BP_DIR/support/build; ls {php,hhvm}-*)
 fi
 engine="php"
 engine_r="php -r"
-if [[ -f "composer.json" ]]; then
-    if [[ ! -f "composer.lock" ]]; then
-        cat composer.json | python -c 'import sys, json; print sys.exit(any(key.count("/") for key in json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your composer.json has dependencies, but no composer.lock
-was found, check it into your repository alongside composer.json!"
+if [[ -f "$COMPOSER" ]]; then
+    if [[ ! -f "$COMPOSER_LOCK" ]]; then
+        cat composer.json | python -c 'import sys, json; sys.exit(bool(json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your '$COMPOSER' lists dependencies inside 'require',
+but no '$COMPOSER_LOCK' was found. Please run 'composer update' to
+re-generate '$COMPOSER_LOCK' if necessary, and commit it into your
+repository. For more information, please refer to the docs at
+https://devcenter.heroku.com/articles/php-support#activation"
     fi
     
     solver_payload=$(echo -n "$runtimes" | python -c '
 import sys, json
 ret = {}
 ret["packages"] = sys.stdin.read().splitlines()
-c_json = dict(json.load(open("composer.json"))) # wrap in dict() to prevent simple errors with {} vs []
-ret["json"] = {k: c_json.get(k, None) for k in ["minimum-stability", "prefer-stable"]}
-ret["json"]["platform"] = {k: dict(c_json.get("require", {})).get(k, None) for k in ["php", "hhvm"]} # wrap in dict() to prevent simple errors with {} vs []
 try:
-    c_lock = json.load(open("composer.lock"))
+    c_lock = json.load(open(sys.argv[1]))
     ret["lock"] = {k: c_lock.get(k, None) for k in ["minimum-stability", "prefer-stable", "stability-flags"]}
     ret["lock"]["platform"] = {k: dict(c_lock.get("platform", {})).get(k, None) for k in ["php", "hhvm"]} # wrap in dict() to prevent simple errors with {} vs []
 except IOError:
     ret["lock"] = None
 print json.dumps(ret)
-' 2> /dev/null) || error "Couldn't parse composer.lock; it must be valid JSON.
+' "$COMPOSER_LOCK" 2> /dev/null) || error "Couldn't parse '$COMPOSER_LOCK'; it must be valid JSON.
 Run 'composer update' to have it re-generated by Composer."
+
+    # warn if minimum-stability is set to non-stable (regardless of whether prefer-stable is used)
+    if echo -n "$solver_payload" | python -c 'import sys, json; p = json.load(sys.stdin); sys.exit(p["lock"] == None or p["lock"]["minimum-stability"] == "stable");' 2> /dev/null; then
+        warning "Your 'composer.json' contains a non-'stable' setting
+for 'minimum-stability'. This may cause the installation of
+unstable versions of runtimes and extensions during this deploy.
+It is recommended that you always use stability flags instead,
+even if you have 'prefer-stable' enabled. For more information,
+see https://getcomposer.org/doc/01-basic-usage.md#stability"
+    fi
+    
     solver_result=$(echo -n "$solver_payload" | curl --silent --location --fail -H'Content-Type: application/json' -H"X-Build-Request-Id: ${REQUEST_ID:-}" -d @- "${RTVS_URL}/resolve?default_runtime=php") || error "Failed to resolve runtime requirements.
 If the issue persists, please contact support."
     while IFS="|" read runtime_name runtime_source runtime_constraint runtime_result; do
+        # make sure we use the correct names for "composer.json" and "composer.lock"
+        case "$runtime_source" in
+            "composer.json")
+                runtime_source="$COMPOSER"
+                ;;
+            "composer.lock")
+                runtime_source="$COMPOSER_LOCK"
+                ;;
+        esac
         if [[ $runtime_result ]]; then
             if [[ $runtime_source == "default" ]]; then
-                status "No runtime required in composer.json, defaulting to ${runtime_name^^} $runtime_result."
+                status "No runtime required in '$COMPOSER', defaulting to ${runtime_name^^} $runtime_result."
             else
-                status "Resolved $runtime_source requirement for ${runtime_name^^} to version ${runtime_result}."
+                status "Resolved '$runtime_source' requirement for ${runtime_name^^} to version ${runtime_result}."
                 if [[ "$runtime_constraint" == "$runtime_result" || "$runtime_constraint" == "=$runtime_result" ]]; then
                     recommended_selector="~$runtime_result"
                     if [[ $runtime_name == "hhvm" ]]; then
                         recommended_selector="${recommended_selector%.*}" # strip "3.2.0" to just "3.2"; HHVM has different versioning
                     fi
-                    warning "Your composer.json requirement for runtime '$runtime_name'
+                    warning "Your '$COMPOSER' requirement for runtime '$runtime_name'
 specifies an exact-match constraint of '$runtime_constraint'.
 This means you will not automatically get more recent compatible
 versions of ${runtime_name^^} on push once they are available. As any such
@@ -149,17 +183,9 @@ will be removed soon. Please upgrade to cedar-14 to continue to
 use HHVM and get access to new releases. For more information,
 see https://devcenter.heroku.com/articles/cedar-14-migration"
                 fi
-                if [[ -f "composer.lock" ]] && python -c 'import sys, json; print sys.exit(any(key.count("hhvm") for key in json.load(open("composer.lock")).get("platform", {})))' 2> /dev/null; then
-                    warning_inline "Support for requiring HHVM in 'composer.json' but not in
-'composer.lock' is deprecated and will be removed soon. Please
-update 'composer.lock' to contain the requirement. If you do not
-have HHVM installed, you can re-generate the lock file using the
-'composer update --ignore-platform-reqs' command; the same switch
-may be used with 'composer install' under the same circumstances."
-                fi
             fi
         else
-            error "Could not resolve $runtime_source requirement for ${runtime_name^^} $runtime_constraint,
+            error "Could not resolve '$runtime_source' requirement for ${runtime_name^^} $runtime_constraint,
 please adjust the selector. The following runtimes are available:
 $(echo $runtimes | fold -s -w 65)"
         fi
@@ -177,7 +203,6 @@ if [[ "${PHP_VERSION}" ]]; then
     PHP_DIST_URL="$S3_URL/php-$PHP_VERSION.tar.gz"
     echo "- PHP $PHP_VERSION" | indent
     curl --silent --location "$PHP_DIST_URL" | tar xz -C $BUILD_DIR/.heroku/php
-    PHP_EXT_DIR=$(php-config --extension-dir)
     # update config files
     mkdir -p $BUILD_DIR/.heroku/php/etc/php
     cp $BP_DIR/conf/php/php.ini $BUILD_DIR/.heroku/php/etc/php
@@ -231,12 +256,12 @@ if [[ "${PHP_VERSION}" ]]; then
     }
     
     exts=()
-    if [[ -f "composer.lock" ]]; then
-        exts=($(cat composer.lock | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
-        ext_source="composer.lock"
+    if [[ -f "$COMPOSER_LOCK" ]]; then
+        exts=($(cat "$COMPOSER_LOCK" | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
+        ext_source="$COMPOSER_LOCK"
     else
-        exts=($(cat composer.json | python -c 'from __future__ import print_function; import sys, json; { print(key[4:].lower()) for key in json.load(sys.stdin)["require"] if key.startswith("ext-")}' 2> /dev/null || true)) # convert to array
-        ext_source="composer.json"
+        exts=($(cat "$COMPOSER" | python -c 'from __future__ import print_function; import sys, json; { print(key[4:].lower()) for key in json.load(sys.stdin)["require"] if key.startswith("ext-")}' 2> /dev/null || true)) # convert to array
+        ext_source="$COMPOSER"
     fi
     for ext in "${!exts[@]}"; do # loop over keys in case the array is empty or else it'll error out
         install_ext "${exts[$ext]}" $ext_source
@@ -281,7 +306,7 @@ composer --version 2> /dev/null | tail -n 1 | indent
 if [[ -e "$(composer config vendor-dir 2> /dev/null | tail -n 1)" ]]; then # tail, as composer echos outdated version warnings to STDOUT
     warning "Your Composer vendor dir is part of your Git repository.
 That directory should not be under version control; only your
-'composer.json' and 'composer.lock' files should be added, which
+'$COMPOSER' and '$COMPOSER_LOCK' files should be added, which
 will let Composer handle installation of dependencies on deploy.
 To suppress this notice, first remove the folder from your index
 by running 'git rm --cached $(composer config vendor-dir 2> /dev/null | tail -n 1)/'.
@@ -313,12 +338,12 @@ fi
 unset COMPOSER_GITHUB_OAUTH_TOKEN
 
 # install dependencies unless composer.json is completely empty (in which case it'd talk to packagist.org which may be slow and is unnecessary)
-cat composer.json | python -c 'import sys,json; sys.exit(not json.load(sys.stdin));' && composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction 2>&1 | indent
+cat "$COMPOSER" | python -c 'import sys,json; sys.exit(not json.load(sys.stdin));' && composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction 2>&1 | indent
 
-composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your composer.json requires 'heroku/heroku-buildpack-php'.
+composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your '$COMPOSER' requires 'heroku/heroku-buildpack-php'.
 This package may only be used as a dependency in 'require-dev'!"
 
-if cat composer.json | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
+if cat "$COMPOSER" | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
     status "Running 'composer compile'..."
     composer run-script --no-dev --no-interaction compile 2>&1 | indent
 fi
